config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/books', to: 'books#index'
  get '/random_background.jpg', to: 'background#image'
  root to: 'welcome#index'

  resources :books, only: [:index, :show, :new, :create, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :authors, only: [:show, :destroy]
  resources :reviews, only: [:destroy]
  resources :users, only: [:show] do
    resources :reviews, only: [:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors, dependent: :destroy

  validates_presence_of :name
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors

  validates_presence_of :title,
                        :publication_year,
                        :pages

  def average_rating
    reviews.average(:rating)
  end

  def review_count
    reviews.count
  end

  def co_authors(author_id)
    authors.where.not(id: author_id)
  end

  def repeat_user(user_id)
    reviews.exists?(user_id: user_id)
  end

  def self.order_average_rating(order_by_rating)
    if order_by_rating == "asc"
      select('books.*, avg(reviews.rating)').joins(:reviews).group('id').order('avg(reviews.rating)')
    elsif order_by_rating == "desc"
      select('books.*, avg(reviews.rating)').joins(:reviews).group('id').order('avg(reviews.rating) DESC')
    end
  end

  def self.order_review_count(order_by_reviews)
    if order_by_reviews == "asc"
      select('books.*, count(reviews.id)').joins(:reviews).group('id').order('count(reviews.id)')
    elsif order_by_reviews == "desc"
      select('books.*, count(reviews.id)').joins(:reviews).group('id').order('count(reviews.id) DESC')
    end
  end

  def self.order_page_count(order_by_pages)
    if order_by_pages == "asc"
      select('books.*').order(:pages)
    elsif order_by_pages == "desc"
      select('books.*').order(pages: :desc)
    end
  end

  def self.highest_rated_books
    select('books.*, avg(reviews.rating)').joins(:reviews).group('id').order('avg(reviews.rating) DESC').limit(3)
  end

  def self.worst_rated_books
    select('books.*, avg(reviews.rating)').joins(:reviews).group('id').order('avg(reviews.rating)').limit(3)
  end

  def self.titles
    select('books.titles').pluck(:title)
  end
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book, dependent: :destroy
  belongs_to :author
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_presence_of :title,
                        :rating,
                        :text

  def self.top_reviews
    select('reviews.*').order(rating: :desc).limit(3)
  end

  def self.bottom_reviews
    select('reviews.*').order(:rating).limit(3)
  end

  def self.top_rated_review
    select('reviews.*').order(rating: :desc).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews

  validates_presence_of :username

  def order_reviews(order_by_date)
    if order_by_date == "oldest"
      reviews.order(created_at: :asc)
    elsif order_by_date == "recent"
      reviews.order(created_at: :desc)
    end
  end

  def review_count
    reviews.count
  end

  def self.top_reviewers
    joins(:reviews).group(:id).order('reviews.count DESC').limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find(params[:id])
  end

  def destroy
    Author.find(params[:id]).destroy
    redirect_to books_path
  end
end

app/controllers/background_controller.rb
class BackgroundController < ApplicationController
  def image
    redirect_to "/assets/background_#{rand(5)}.jpg"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @highest_rated_books = Book.highest_rated_books
    @worst_rated_books = Book.worst_rated_books
    @top_reviewers = User.top_reviewers
    if params[:order_by_rating]
      @books = Book.order_average_rating(params[:order_by_rating])
    elsif params[:order_by_reviews]
      @books = Book.order_review_count(params[:order_by_reviews])
    elsif params[:order_by_pages]
      @books = Book.order_page_count(params[:order_by_pages])
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    book_title = book_params[:title].strip.downcase.titleize
    books = Book.all
    if books.titles.include?(book_title) || book_params[:pages].to_i <= 0 || book_params == nil
      flash.notice = "Invalid entry. Please try again."
      redirect_to new_book_path
    else
      book = Book.new(book_params)
      book.update(title: book_title)
      if book.cover_image == ""
        book.cover_image = "/assets/book_default.png"
      end
      authors = author_params[:authors].titleize.split(", ")
      authors.each do |author|
        book.authors << Author.find_or_create_by(name: author)
      end
      book.save
      redirect_to book_path(book)
    end
  end

  def destroy
    @book = Book.all
    @book.destroy(params[:id])
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :publication_year, :pages, :cover_image)
  end

  def author_params
    params.require(:book).permit(:authors)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  def create
    book = Book.find(params[:book_id])
    user = User.find_or_create_by(username: params[:review][:user].strip.downcase.titleize)
    review = user.reviews.new(review_params)
    if book.repeat_user(user.id) || review_params.values.include?("") || user.username == ""
      flash.notice = "Error."
      redirect_to book_path(book)
    else
      review.save
      book.reviews << review
      redirect_to book_path(book)
    end
  end

  def destroy
    @review = Review.find(params[:id])
    user = @review.user
    @review.destroy
    redirect_to user_path(user)
  end

  private

  def review_params
    params.require(:review).permit(:title, :rating, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if params[:order_by_date]
      @reviews = @user.order_reviews(params[:order_by_date])
    else
      @reviews = @user.reviews
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/show.html.erb
<body class="index">
<h1><%= @author.name %></h1>
<% @author.books.each do |book| %>
  <section id="book-<%= book.id %>">
    <h2><%= link_to book.title, book_path(book) %></h2>
    <img src="<%= book.cover_image %>" alt= "<%= book.title %>" height="150" width="100"/>
    <p>Pages: <%= book.pages %><br>
    Year: <%= book.publication_year %><br>
    <% book.co_authors(@author.id).each do |author| %>
      Co-author: <%= link_to author.name, author_path(author) %><br>
    <% end %></p>
    <% if book.reviews.first != nil %>
      <% top_review = book.reviews.top_rated_review %>
      <p id="top-rated-review-<%= book.id %>">Top Rated Review: "<%= top_review.title %>"(<%= top_review.rating %>)
        by <%= link_to top_review.user.username, user_path(top_review.user) %></p>
    <% else %>
      <p>No reviews for this book. Be the first to leave a review!</p>
    <% end %>
  </section>
<% end %>
<p><%= link_to 'Delete this Author', author_path(@author), method: :delete %></p>
</body>

app/views/books/index.html.erb
  <ul class="nav_bar">
    <li class="nav_bar"><a class = "active" href='/'>Home</a></li>
    <li class="nav_bar"><a href='/books'>Book List</a></li>
    <li class="nav_bar"><a href='/books/new'>Add New Book</a></li>
    <li class="nav_bar"><a href='/books?order_by_rating=asc'>Average Rating ascending</a></li>
    <li class="nav_bar"><a href='/books?order_by_rating=desc'>Average Rating descending</a></li>
    <li class="nav_bar"><a href='/books?order_by_reviews=asc'>Number of Reviews ascending</a></li>
    <li class="nav_bar"><a href='/books?order_by_reviews=desc'>Number of Reviews descending</a></li>
    <li class="nav_bar"><a href='/books?order_by_pages=asc'>Page Number ascending</a></li>
    <li class="nav_bar"><a href='/books?order_by_pages=desc'>Page Number descending</a></li>
  </ul>
<body class="index">
<style>*{text-decoration:none; color:white; text-shadow:2px 4px 4px rgba(0, 0, 0, 0.7);}</style>
<h1>Book List</h1>
<section id="books_list">
  <% @books.each do |book| %>
  <li class="column">
     <section id='book-<%= book.id %>' >
       <img src=<%= book.cover_image %> alt= "<%= book.title %>" height="300" width="200" /><br>
        <%= link_to book.title, book_path(book) %><br>
        <% book.authors.each do |author| %>
          By: <%= link_to author.name, author_path(author) %><br>
        <% end %>
        <div>Publication Year: <%= book.publication_year %><br>
        Pages: <%= book.pages %><br>
        Reviews: <%= book.review_count %><br>
        Average Rating: <%= book.average_rating.to_f.round(1) %></div>
      </section>
    </li>
  <% end %>

<h1>Statistics</h1>
  <section class='statistics-highest-rated-book-'>
<h3>Highest Rated Books (Top 3):</h3>
    <% @highest_rated_books.each do |book| %>
      <p>Title: <%= link_to book.title, book_path(book) %></p>
      <p>Average Rating: <%= book.average_rating.to_f.round(1) %></p>
    <% end %>
  </section>
  <h3>Worst Rated Books (Bottom 3):</h3>
  <section class='statistics-worst-rated-book-'>
    <% @worst_rated_books.each do |book| %>
      <p>Title: <%= link_to book.title, book_path(book) %></p>
      <p>Average Rating: <%= book.average_rating.to_f.round(1) %></p>
    <% end %>
  </section>
  <h3>Users with the Most Reviews:</h3>
  <section id='statistics-most-user-reviews'>
    <% @top_reviewers.each do |user| %>
      <p>Username: <%= link_to user.username, user_path(user) %></p>
      <p>Reviews: <%= user.review_count %></p>
    <% end %>
  </section>
</body>

app/views/books/new.html.erb
<body class="index">
<h1>New Book</h1>

<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :publication_year %>
  <%= f.number_field :publication_year %><br>

  <%= f.label :pages %>
  <%= f.number_field :pages %><br>

  <%= f.label :cover_image %>
  <%= f.url_field :cover_image %><br>

  <%= f.label :authors %>
  <%= f.text_field :authors, :placeholder=> "author, author2, author3...", :value => "" %><br>

  <%= f.submit %>
<% end %>
</body>

app/views/books/show.html.erb
<body class="index">
<h1><%= @book.title %></h1>
<% @book.authors.each do |author| %>
  <p id="author-<%= author.id %>">By: <%= link_to author.name, author_path(author) %></p>
<% end %>
  <p>Publication Year: <%= @book.publication_year %></p>
  <p>Pages: <%= @book.pages %></p>
  <img src=<%= @book.cover_image %> alt= "<%= @book.title %>" height="150" width="100"/>
  <p><%= link_to 'Delete this Book', book_path(@book), method: :delete %></p>

<h2>Reviews</h2>
<p><%= link_to "Write a Review", new_book_review_path(@book) %></p>

  <% @book.reviews.each do |review| %>
    <section id="review-info-<%= review.id %>">
      <p>Review Title: <%= review.title %></p>
      <p>Reviewer: <%= link_to review.user.username, user_path(review.user) %></p>
      <p>Rating: <%= review.rating %></p>
      <p>Comments: <%= review.text %></p>
    </section>
  <% end %>

<h2>Statistics</h2>
  <h3><%= @book.average_rating.to_f.round(1) %></h3>
    <section id="top-reviews">
      <h3>Top Reviews</h3>
      <% @book.reviews.top_reviews.each do |review| %>
        <h4><%= review.user.username %></h4>
        <h4><%= review.title %> (<%= review.rating %>)</h4>
      <% end %>
    </section>
    <section id="bottom-reviews">
      <h3>Bottom Reviews</h3>
      <% @book.reviews.bottom_reviews.each do |review| %>
        <h4><%= review.user.username %></h4>
        <h4><%= review.title %> (<%= review.rating %>)</h4>
      <% end %>
    </section>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="book_icon.png">
    <link href="https://fonts.googleapis.com/css?family=Exo|Pacifico" rel="stylesheet">
    <link rel="stylesheet" href="application.css">
    <title>Lit Cove Book Club</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <style>

  ul.nav_bar {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
    position: -webkit-sticky; /* Safari */
    position: sticky;
    top: 0;
  }

  li.nav_bar {
    float: left;
    font-family: 'Exo';
  }

  li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }

  li a:hover {
    background-color: #111;
  }

  .active {
    background-color: #4CAF50;
  }
  </style>

  <body>
    <% unless current_page?(root_path) || current_page?(books_path) %>
      <ul class="nav_bar">
        <li class="nav_bar"><a class = "active" href="/">Home</a></li>
        <li class="nav_bar"><a href="/books">Book List</a></li>
      </ul>
    <% end %>
    <p class="flash" ><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<body class="index">
<h1>New Review</h1>

<%= form_for [@book, @review] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :username %>
  <%= f.text_field :user %><br>

  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %><br>

  <%= f.label :text %>
  <%= f.text_field :text %><br>

  <%= f.submit "Submit Review" %>
<% end %>
</body>

app/views/users/show.html.erb
<body class="index">
<h1><%= @user.username %></h1>
<p><a class="button" href="<%= user_path(@user) + "?order_by_date=recent" %>">Most Recent - Reviews</a></p>
<p><a class="button" href="<%= user_path(@user) + "?order_by_date=oldest" %>">Oldest - Reviews</a></p>

<% @reviews.each do |review| %>
<section id="review-<%= review.id %>">

  <h2><%= review.title %></h2>
  <p> <%= review.book.title %></p>
  <img src="<%= review.book.cover_image %>" alt= "<%= review.book.title %>" height="150" width="100"/>
  <p><%= review.text %></p>
  <p><%= review.rating %></p>
  <p><%= review.created_at.to_formatted_s(:long).slice(0...-6) %></p>
  <p><%= link_to 'Delete this Review', review_path(review), method: :delete %></p>
  </section>
<% end %>
</body>

app/views/welcome/index.html.erb
<body class="welcome">
  <link href="https://fonts.googleapis.com/css?family=Exo|Pacifico" rel="stylesheet">
  <link rel="stylesheet" href="application.css">
  <br>
  <br>
  <h1>Welcome to The Lit Cove Book Club</h1>

  <a class="button" href="<%= books_path %>">Enter Here</a>

</body>